import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';



export default function Home() {
  const [count, setCount] = useState(0);
  const [isec2, setIsec2] = useState(0);
  const [instanceType,setInstanceType] = useState(0);
  const checkVal = (value)=>{
        if(value === 'aws_instance'){
        setInstanceType(1);}
        
  }
  return (
    <div>
      <Head>
        <title>Dev One Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" />
      </Head>      
      <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">DevOneCloud</a>
    </div>
  </div>
</nav>
      <div className="content">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-10">
              <div className="row align-items-center">
                <div className="col-lg-7 mb-5 mb-lg-0">
                  <h2 className="mb-5">Fill the form. <br /> It's easy.</h2>
                  <div className="row">
                  <div className="col-md-2">
                  <button type="button" class="btn btn-primary" onClick={() => setCount(1)}>AWS</button>
                  </div>
                  <div className="col-md-2">
                  <button type="button" class="btn btn-primary"  >Azure</button>
                  </div>
                  <div className="col-md-2">
                  <button type="button" class="btn btn-primary" >GCP</button>
                  </div> 
                  </div>
                  <br />
                  <div style={count?{display:"block"}:{display:"none"}}>Provider</div>
                  <br/>
                  <div className="row">
                  <div className="col-md-2">
                  <button type="button" class="btn btn-outline-info" style={count?{display:"block"}:{display:"none"}} onClick={() => setIsec2(1) }>EC2</button>
                  </div>
                  <div className="col-md-2">
                  <button type="button" class="btn btn-outline-info" style={count?{display:"block"}:{display:"none"}}>S3</button>
                  </div>
                  </div>
                  <br />
                  <form className="border-right pr-5 mb-5" action="/api/form" method="post">

                  <div style={isec2?{display:"block"}:{display:"none"}} >
                    Resources : 
                  <div>
                        <select name="resource_type" id="resource_type" onChange={(e)=> checkVal(e.target.value)}>
                        <option value="" selected disabled >Resouce Type</option>
                            <option value="aws_instance" >aws_instance</option>
                            <option value="aws_iam_user">aws_iam_user</option>
                            <option value="aws_iam_role">aws_iam_role</option>
                            <option value="aws_iam_policy">aws_iam_policy</option>
                            <option value="aws_iam_group">aws_iam_group</option>
                          </select>
                          </div>                 
                          <br />
                  </div>

                  <div style={instanceType?{display:"block"}:{display:"none"}}>
                    <div className="row">
                      <div className="col-md-6 form-group">
                      <select name="instance_type" id="instance_type" >
                      <option value="" selected disabled>Instance Type</option>
                            <option value="t3.micro">t3.micro</option>
                            <option value="t3.nano">t3.nano</option>
                            <option value="t3.small">t3.small</option>

                          </select>
                      </div>
                      </div>
                      <br/>
                      <div className="col-md-6 form-group">
                        <input type="text" className="form-control" name="instance_name" id="instance_name" placeholder="Instance Name" />
                      </div>


                    <div className="row">
                      <div className="col-md-12">
                        <input type="submit" className="btn btn-primary rounded-0 py-2 px-4" />
                        <span className="submitting" />
                      </div>
                    </div>

                    </div>

                  </form>

                </div>
                <div className="col-lg-4 ml-auto">
                  <h3 className="mb-4">Let's talk about everything.</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil deleniti itaque similique magni. Magni, laboriosam perferendis maxime!</p>
                  <p><a href="#">Read more</a></p>
                </div>
              </div>
            </div>  
          </div>
        </div>
      </div>
     </div>
  )
}
